package server

import (
	"bytes"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
)

func TestConvertAPI(t *testing.T) {
	mux := http.NewServeMux()
	Register(mux)
	body := bytes.NewBufferString(`{"mode":"json-go","input":"{\"id\":1}"}`)
	req := httptest.NewRequest(http.MethodPost, "/api/convert", body)
	rec := httptest.NewRecorder()

	mux.ServeHTTP(rec, req)

	if rec.Code != http.StatusOK {
		t.Fatalf("status = %d, body = %s", rec.Code, rec.Body.String())
	}
	if !strings.Contains(rec.Body.String(), "type AutoGenerated struct") {
		t.Fatalf("response missing generated struct: %s", rec.Body.String())
	}
}
