package convert

import (
	"fmt"
	"strings"

	"github.com/schemaforge/schemaforge/internal/generator"
	"github.com/schemaforge/schemaforge/internal/parser"
)

type Mode string

const (
	ModeJSONGo   Mode = "json-go"
	ModeYAMLGo   Mode = "yaml-go"
	ModeXMLJSON  Mode = "xml-json"
	ModeSQLEnt   Mode = "sql-ent"
	ModeSQLGORM  Mode = "sql-gorm"
	ModeSQLES    Mode = "sql-es"
	ModeSQLMongo Mode = "sql-mongo"
)

type Request struct {
	Mode  Mode   `json:"mode"`
	Input string `json:"input"`
}

type Response struct {
	Mode   Mode   `json:"mode"`
	Output string `json:"output"`
}

func Convert(req Request) (Response, error) {
	input := strings.TrimSpace(req.Input)
	if input == "" {
		return Response{}, fmt.Errorf("input is empty")
	}

	var out string
	var err error

	switch req.Mode {
	case ModeJSONGo:
		out, err = generator.GoStructFromJSON(input, "AutoGenerated")
	case ModeYAMLGo:
		value, parseErr := parser.ParseYAML(input)
		if parseErr != nil {
			return Response{}, parseErr
		}
		out, err = generator.GoStructFromValue(value, "AutoGenerated")
	case ModeXMLJSON:
		out, err = generator.JSONFromXML(input)
	case ModeSQLEnt, ModeSQLGORM, ModeSQLES, ModeSQLMongo:
		tables, parseErr := parser.ParseMySQLDDL(input)
		if parseErr != nil {
			return Response{}, parseErr
		}
		switch req.Mode {
		case ModeSQLEnt:
			out, err = generator.EntSchemas(tables)
		case ModeSQLGORM:
			out, err = generator.GORMModels(tables)
		case ModeSQLES:
			out, err = generator.ESMappings(tables)
		case ModeSQLMongo:
			out, err = generator.MongoSchemas(tables)
		}
	default:
		return Response{}, fmt.Errorf("unsupported mode %q", req.Mode)
	}
	if err != nil {
		return Response{}, err
	}
	return Response{Mode: req.Mode, Output: out}, nil
}

func Modes() []Mode {
	return []Mode{ModeJSONGo, ModeYAMLGo, ModeXMLJSON, ModeSQLEnt, ModeSQLGORM, ModeSQLES, ModeSQLMongo}
}
