package convert

import (
	"encoding/json"
	"fmt"
	"reflect"
	"strings"

	"github.com/why19970628/schemaforge/internal/generator"
	"github.com/why19970628/schemaforge/internal/parser"
)

type Mode string
type Format string

const (
	ModeJSONGo   Mode = "json-go"
	ModeJSONDiff Mode = "json-diff"
	ModeYAMLGo   Mode = "yaml-go"
	ModeXMLJSON  Mode = "xml-json"
	ModeSQLEnt   Mode = "sql-ent"
	ModeSQLGORM  Mode = "sql-gorm"
	ModeSQLES    Mode = "sql-es"
	ModeSQLMongo Mode = "sql-mongo"
)

const (
	FormatStructured Format = "structured"
	FormatUnified    Format = "unified"
)

type Request struct {
	Mode    Mode              `json:"mode"`
	Input   string            `json:"input"`
	Right   string            `json:"right"`
	Format  Format            `json:"format"`
	Options generator.Options `json:"options"`
}

type Response struct {
	Mode   Mode   `json:"mode"`
	Output string `json:"output"`
}

func Convert(req Request) (Response, error) {
	input := strings.TrimSpace(req.Input)
	if input == "" {
		return Response{}, fmt.Errorf("input is empty")
	}

	var out string
	var err error

	switch req.Mode {
	case ModeJSONGo:
		out, err = generator.GoStructFromJSON(input, "AutoGenerated")
	case ModeJSONDiff:
		out, err = jsonDiff(input, strings.TrimSpace(req.Right), req.Format)
	case ModeYAMLGo:
		value, parseErr := parser.ParseYAML(input)
		if parseErr != nil {
			return Response{}, parseErr
		}
		out, err = generator.GoStructFromValue(value, "AutoGenerated")
	case ModeXMLJSON:
		out, err = generator.JSONFromXML(input)
	case ModeSQLEnt, ModeSQLGORM, ModeSQLES, ModeSQLMongo:
		tables, parseErr := parser.ParseMySQLDDL(input)
		if parseErr != nil {
			return Response{}, parseErr
		}
		switch req.Mode {
		case ModeSQLEnt:
			out, err = generator.EntSchemas(tables)
		case ModeSQLGORM:
			if req.Options == (generator.Options{}) {
				out, err = generator.GORMModels(tables)
			} else {
				out, err = generator.GORMModelsWithOptions(tables, req.Options)
			}
		case ModeSQLES:
			out, err = generator.ESMappings(tables)
		case ModeSQLMongo:
			out, err = generator.MongoSchemas(tables)
		}
	default:
		return Response{}, fmt.Errorf("unsupported mode %q", req.Mode)
	}
	if err != nil {
		return Response{}, err
	}
	return Response{Mode: req.Mode, Output: out}, nil
}

func Modes() []Mode {
	return []Mode{ModeJSONGo, ModeJSONDiff, ModeYAMLGo, ModeXMLJSON, ModeSQLEnt, ModeSQLGORM, ModeSQLES, ModeSQLMongo}
}

type jsonDiffResult struct {
	Added       []jsonDiffAdded       `json:"added"`
	Removed     []jsonDiffRemoved     `json:"removed"`
	Changed     []jsonDiffChanged     `json:"changed"`
	TypeChanged []jsonDiffTypeChanged `json:"type_changed"`
}

type jsonDiffAdded struct {
	Path  string `json:"path"`
	Value any    `json:"value"`
}

type jsonDiffRemoved struct {
	Path  string `json:"path"`
	Value any    `json:"value"`
}

type jsonDiffChanged struct {
	Path string `json:"path"`
	From any    `json:"from"`
	To   any    `json:"to"`
}

type jsonDiffTypeChanged struct {
	Path     string `json:"path"`
	FromType string `json:"from_type"`
	ToType   string `json:"to_type"`
	From     any    `json:"from"`
	To       any    `json:"to"`
}

func jsonDiff(leftText, rightText string, format Format) (string, error) {
	if rightText == "" {
		return "", fmt.Errorf("right input is empty")
	}
	var left any
	if err := json.Unmarshal([]byte(leftText), &left); err != nil {
		return "", fmt.Errorf("left json: %w", err)
	}
	var right any
	if err := json.Unmarshal([]byte(rightText), &right); err != nil {
		return "", fmt.Errorf("right json: %w", err)
	}
	if format == FormatUnified {
		return unifiedJSONDiff(left, right)
	}
	result := jsonDiffResult{
		Added:       []jsonDiffAdded{},
		Removed:     []jsonDiffRemoved{},
		Changed:     []jsonDiffChanged{},
		TypeChanged: []jsonDiffTypeChanged{},
	}
	diffJSONValue("$", left, right, &result)
	data, err := json.MarshalIndent(result, "", "  ")
	if err != nil {
		return "", err
	}
	return string(data), nil
}

func unifiedJSONDiff(left, right any) (string, error) {
	leftJSON, err := json.MarshalIndent(left, "", "  ")
	if err != nil {
		return "", err
	}
	rightJSON, err := json.MarshalIndent(right, "", "  ")
	if err != nil {
		return "", err
	}
	leftLines := strings.Split(string(leftJSON), "\n")
	rightLines := strings.Split(string(rightJSON), "\n")
	diffLines := unifiedLines(leftLines, rightLines)
	return strings.Join(diffLines, "\n"), nil
}

func unifiedLines(leftLines, rightLines []string) []string {
	lcs := make([][]int, len(leftLines)+1)
	for i := range lcs {
		lcs[i] = make([]int, len(rightLines)+1)
	}
	for i := len(leftLines) - 1; i >= 0; i-- {
		for j := len(rightLines) - 1; j >= 0; j-- {
			if leftLines[i] == rightLines[j] {
				lcs[i][j] = lcs[i+1][j+1] + 1
			} else if lcs[i+1][j] >= lcs[i][j+1] {
				lcs[i][j] = lcs[i+1][j]
			} else {
				lcs[i][j] = lcs[i][j+1]
			}
		}
	}

	out := []string{"--- left.json", "+++ right.json", "@@"}
	i, j := 0, 0
	for i < len(leftLines) && j < len(rightLines) {
		if leftLines[i] == rightLines[j] {
			out = append(out, " "+leftLines[i])
			i++
			j++
			continue
		}
		if lcs[i+1][j] >= lcs[i][j+1] {
			out = append(out, "-"+leftLines[i])
			i++
		} else {
			out = append(out, "+"+rightLines[j])
			j++
		}
	}
	for ; i < len(leftLines); i++ {
		out = append(out, "-"+leftLines[i])
	}
	for ; j < len(rightLines); j++ {
		out = append(out, "+"+rightLines[j])
	}
	return out
}

func diffJSONValue(path string, left, right any, result *jsonDiffResult) {
	leftKind := jsonValueKind(left)
	rightKind := jsonValueKind(right)
	if leftKind != rightKind {
		result.TypeChanged = append(result.TypeChanged, jsonDiffTypeChanged{
			Path:     path,
			FromType: leftKind,
			ToType:   rightKind,
			From:     left,
			To:       right,
		})
		return
	}
	switch leftValue := left.(type) {
	case map[string]any:
		rightValue := right.(map[string]any)
		for key, rightChild := range rightValue {
			childPath := jsonObjectPath(path, key)
			leftChild, ok := leftValue[key]
			if !ok {
				result.Added = append(result.Added, jsonDiffAdded{Path: childPath, Value: rightChild})
				continue
			}
			diffJSONValue(childPath, leftChild, rightChild, result)
		}
		for key, leftChild := range leftValue {
			if _, ok := rightValue[key]; !ok {
				result.Removed = append(result.Removed, jsonDiffRemoved{Path: jsonObjectPath(path, key), Value: leftChild})
			}
		}
	case []any:
		rightValue := right.([]any)
		common := len(leftValue)
		if len(rightValue) < common {
			common = len(rightValue)
		}
		for i := 0; i < common; i++ {
			diffJSONValue(fmt.Sprintf("%s[%d]", path, i), leftValue[i], rightValue[i], result)
		}
		for i := common; i < len(rightValue); i++ {
			result.Added = append(result.Added, jsonDiffAdded{Path: fmt.Sprintf("%s[%d]", path, i), Value: rightValue[i]})
		}
		for i := common; i < len(leftValue); i++ {
			result.Removed = append(result.Removed, jsonDiffRemoved{Path: fmt.Sprintf("%s[%d]", path, i), Value: leftValue[i]})
		}
	default:
		if !reflect.DeepEqual(left, right) {
			result.Changed = append(result.Changed, jsonDiffChanged{Path: path, From: left, To: right})
		}
	}
}

func jsonValueKind(value any) string {
	switch value.(type) {
	case nil:
		return "null"
	case bool:
		return "boolean"
	case float64:
		return "number"
	case string:
		return "string"
	case []any:
		return "array"
	case map[string]any:
		return "object"
	default:
		return fmt.Sprintf("%T", value)
	}
}

func jsonObjectPath(parent, key string) string {
	if isJSONPathIdentifier(key) {
		return parent + "." + key
	}
	return fmt.Sprintf("%s[%q]", parent, key)
}

func isJSONPathIdentifier(value string) bool {
	if value == "" {
		return false
	}
	for index, r := range value {
		if r == '_' || r >= 'a' && r <= 'z' || r >= 'A' && r <= 'Z' || index > 0 && r >= '0' && r <= '9' {
			continue
		}
		return false
	}
	return true
}
