package convert_test

import (
	"strings"
	"testing"

	"github.com/schemaforge/schemaforge/internal/convert"
)

func TestConvertJSONToGo(t *testing.T) {
	resp, err := convert.Convert(convert.Request{Mode: convert.ModeJSONGo, Input: `{"id":1,"name":"Ada","active":true}`})
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{"type AutoGenerated struct", "ID", "int64", "`json:\"id\"`", "Name", "`json:\"name\"`", "Active", "`json:\"active\"`"} {
		if !strings.Contains(resp.Output, want) {
			t.Fatalf("output missing %q:\n%s", want, resp.Output)
		}
	}
}

func TestConvertSQLTargets(t *testing.T) {
	sql := "CREATE TABLE `users` (`id` bigint NOT NULL AUTO_INCREMENT COMMENT 'id', `email` varchar(255) NOT NULL COMMENT 'email', `age` int DEFAULT 0, PRIMARY KEY (`id`), UNIQUE KEY `uk_email` (`email`)) COMMENT='users';"
	cases := map[convert.Mode][]string{
		convert.ModeSQLEnt:   {"type User struct", "field.String(\"email\")", "index.Fields(\"email\").Unique()"},
		convert.ModeSQLGORM:  {"type User struct", "Email string `gorm:\"column:email;type:varchar(255);not null;uniqueIndex\" json:\"email\"`"},
		convert.ModeSQLES:    {"\"users\"", "\"email\"", "\"type\": \"keyword\""},
		convert.ModeSQLMongo: {"\"$jsonSchema\"", "\"email\"", "\"bsonType\": \"string\""},
	}
	for mode, wants := range cases {
		resp, err := convert.Convert(convert.Request{Mode: mode, Input: sql})
		if err != nil {
			t.Fatalf("%s: %v", mode, err)
		}
		for _, want := range wants {
			if !strings.Contains(resp.Output, want) {
				t.Fatalf("%s output missing %q:\n%s", mode, want, resp.Output)
			}
		}
	}
}

func TestConvertXMLToJSON(t *testing.T) {
	resp, err := convert.Convert(convert.Request{Mode: convert.ModeXMLJSON, Input: `<user id="1"><name>Ada</name></user>`})
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{`"user"`, `"@id": "1"`, `"name": "Ada"`} {
		if !strings.Contains(resp.Output, want) {
			t.Fatalf("output missing %q:\n%s", want, resp.Output)
		}
	}
}
