package generator

import (
	"strings"
	"testing"
)

func TestGoStructFromJSONNestedObjectAndArray(t *testing.T) {
	out, err := GoStructFromJSON(`{"id":1,"profile":{"city":"Hangzhou"},"tags":["go"]}`, "AutoGenerated")
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{"type AutoGenerated struct", "ID", "Profile Profile", "Tags", "[]string", "type Profile struct"} {
		if !strings.Contains(out, want) {
			t.Fatalf("missing %q:\n%s", want, out)
		}
	}
}

func TestGoStructFromJSONRejectsNonObjectRoot(t *testing.T) {
	if _, err := GoStructFromJSON(`[1,2,3]`, "AutoGenerated"); err == nil {
		t.Fatal("expected error")
	}
}
