package generator

import (
	"strings"
	"unicode"
)

var initialisms = map[string]string{
	"api":   "API",
	"id":    "ID",
	"json":  "JSON",
	"url":   "URL",
	"uuid":  "UUID",
	"xml":   "XML",
	"yaml":  "YAML",
	"html":  "HTML",
	"http":  "HTTP",
	"https": "HTTPS",
}

func exportName(s string) string {
	parts := strings.FieldsFunc(s, func(r rune) bool {
		return r == '_' || r == '-' || r == ' ' || r == '.'
	})
	var out strings.Builder
	for _, part := range parts {
		if part == "" {
			continue
		}
		if isExportedMixedCase(part) {
			out.WriteString(part)
			continue
		}
		lower := strings.ToLower(part)
		if value, ok := initialisms[lower]; ok {
			out.WriteString(value)
			continue
		}
		runes := []rune(lower)
		runes[0] = unicode.ToUpper(runes[0])
		out.WriteString(string(runes))
	}
	if out.Len() == 0 {
		return "AutoGenerated"
	}
	return out.String()
}

func isExportedMixedCase(s string) bool {
	runes := []rune(s)
	if len(runes) < 2 || !unicode.IsUpper(runes[0]) {
		return false
	}
	for _, r := range runes[1:] {
		if unicode.IsUpper(r) {
			return true
		}
	}
	return false
}

func singularTableName(name string) string {
	if strings.HasSuffix(name, "ies") && len(name) > 3 {
		return strings.TrimSuffix(name, "ies") + "y"
	}
	if strings.HasSuffix(name, "ses") {
		return strings.TrimSuffix(name, "es")
	}
	if strings.HasSuffix(name, "s") && len(name) > 1 {
		return strings.TrimSuffix(name, "s")
	}
	return name
}

func lowerFirst(s string) string {
	if s == "" {
		return s
	}
	runes := []rune(s)
	runes[0] = unicode.ToLower(runes[0])
	return string(runes)
}
